//! Embedded stdlib files for use when no stdlib directory is available on disk.
//! Generated from crates/ato-sema/stdlib/

/// Returns a list of (filename, contents) for all stdlib .ato files.
pub fn embedded_stdlib_files() -> Vec<(&'static str, &'static str)> {
    vec![
        ("Addressor.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/Addressor.ato"))),
        ("BJT.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/BJT.ato"))),
        ("CAN.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/CAN.ato"))),
        ("Capacitor.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/Capacitor.ato"))),
        ("Connector.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/Connector.ato"))),
        ("Crystal.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/Crystal.ato"))),
        ("DifferentialPair.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/DifferentialPair.ato"))),
        ("Diode.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/Diode.ato"))),
        ("ElectricLogic.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/ElectricLogic.ato"))),
        ("ElectricPower.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/ElectricPower.ato"))),
        ("ElectricSignal.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/ElectricSignal.ato"))),
        ("Electrical.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/Electrical.ato"))),
        ("Ferrite.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/Ferrite.ato"))),
        ("Fuse.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/Fuse.ato"))),
        ("I2C.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/I2C.ato"))),
        ("I2S.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/I2S.ato"))),
        ("Inductor.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/Inductor.ato"))),
        ("JTAG.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/JTAG.ato"))),
        ("LDO.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/LDO.ato"))),
        ("LED.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/LED.ato"))),
        ("MOSFET.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/MOSFET.ato"))),
        ("MultiSPI.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/MultiSPI.ato"))),
        ("OpAmp.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/OpAmp.ato"))),
        ("PDM.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/PDM.ato"))),
        ("Power.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/Power.ato"))),
        ("PoweredLED.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/PoweredLED.ato"))),
        ("Regulator.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/Regulator.ato"))),
        ("Relay.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/Relay.ato"))),
        ("Resistor.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/Resistor.ato"))),
        ("ResistorVoltageDivider.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/ResistorVoltageDivider.ato"))),
        ("SPI.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/SPI.ato"))),
        ("SWD.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/SWD.ato"))),
        ("Signal.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/Signal.ato"))),
        ("Switch.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/Switch.ato"))),
        ("TVS.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/TVS.ato"))),
        ("TestPoint.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/TestPoint.ato"))),
        ("UART.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/UART.ato"))),
        ("USB.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/USB.ato"))),
        ("XtalIF.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/XtalIF.ato"))),
        ("Zener.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/Zener.ato"))),
        ("can_bridge.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/can_bridge.ato"))),
        ("can_bridge_by_name.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/can_bridge_by_name.ato"))),
        ("has_datasheet.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/has_datasheet.ato"))),
        ("has_datasheet_defined.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/has_datasheet_defined.ato"))),
        ("has_designator_prefix.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/has_designator_prefix.ato"))),
        ("has_part_picked.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/has_part_picked.ato"))),
        ("has_part_removed.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/has_part_removed.ato"))),
        ("has_single_electric_reference.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/has_single_electric_reference.ato"))),
        ("has_single_electric_reference_shared.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/has_single_electric_reference_shared.ato"))),
        ("is_atomic_part.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/is_atomic_part.ato"))),
        ("is_auto_generated.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/is_auto_generated.ato"))),
        ("regulators.ato", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/stdlib/regulators.ato"))),
    ]
}
