[package]
name = "ato-tests"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
ato-lexer = { workspace = true }
ato-parser = { workspace = true }
ato-domain = { workspace = true }
ato-solver = { workspace = true }
ato-ir = { workspace = true }
ato-sema = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
ato-export = { workspace = true }
insta = { workspace = true }
walkdir = { workspace = true }
tempfile = "3"
